Optimize the recognition of device names

diff --git a/amlogic-s9xxx/common-files/files/usr/bin/openwrt-install b/amlogic-s9xxx/common-files/files/usr/bin/openwrt-install
--- a/amlogic-s9xxx/common-files/files/usr/bin/openwrt-install
+++ b/amlogic-s9xxx/common-files/files/usr/bin/openwrt-install
@@ -1,6 +1,6 @@
 #!/bin/bash
 #======================================================================================
-# Function: Install openwrt to emmc for Amlogic S9xxx STB
+# Function: Install OpenWrt to emmc for Amlogic S9xxx STB
 # Copyright (C) 2020-2021 Flippy
 # Copyright (C) 2020-2021 https://github.com/lasthinker/amlogic-s9xxx-openwrt
 #======================================================================================
@@ -42,7 +42,10 @@ echo "SPECIFY_DTB: ${SPECIFY_DTB}"
 # Current device model
 MYDEVICE_NAME=$(cat /proc/device-tree/model 2>/dev/null)
 if [[ -z "${MYDEVICE_NAME}" ]]; then
-    echo "Unknown device"
+    echo "The device name is empty and cannot be recognized."
+    exit 1
+elif [[ -f "/etc/flippy-openwrt-release" ]]; then
+    echo "The [ /etc/flippy-openwrt-release ] file is missing."
     exit 1
 else
     echo -e "Current device: ${MYDEVICE_NAME} [ amlogic ]"
