Upstream changes

diff --git a/make-openwrt/openwrt-files/common-files/usr/sbin/openwrt-tf b/make-openwrt/openwrt-files/common-files/usr/sbin/openwrt-tf
--- a/make-openwrt/openwrt-files/common-files/usr/sbin/openwrt-tf
+++ b/make-openwrt/openwrt-files/common-files/usr/sbin/openwrt-tf
@@ -15,8 +15,13 @@
 #
 #========================= Set default parameters ===========================
 #
+# Automatically expand file
+todo_rootfs_resize="/root/.todo_rootfs_resize"
+#
+# Set font color
 STEPS="[\033[95m STEPS \033[0m]"
 INFO="[\033[94m INFO \033[0m]"
+TIPS="[\033[93m TIPS \033[0m]"
 SUCCESS="[\033[92m SUCCESS \033[0m]"
 OPTIONS="[\033[93m OPTIONS \033[0m]"
 ERROR="[\033[91m ERROR \033[0m]"
@@ -38,17 +43,17 @@ do_checkdisk() {
     # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
     case "${ROOT_PTNAME}" in
     mmcblk?p[1-4])
-        DISK_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')"
+        DISK_NAME="${ROOT_PTNAME:0:-2}"
         PT_PRE="${DISK_NAME}p"
-        LB_PRE="EMMC_"
+        LB_PRE="MMC_"
         ;;
     [hsv]d[a-z][1-4])
-        DISK_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')"
+        DISK_NAME="${ROOT_PTNAME:0:-1}"
         PT_PRE="${DISK_NAME}"
         LB_PRE="USB_"
         ;;
     nvme?n?p[1-4])
-        DISK_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')"
+        DISK_NAME="${ROOT_PTNAME:0:-2}"
         PT_PRE="${DISK_NAME}p"
         LB_PRE="NVME_"
         ;;
@@ -56,63 +61,65 @@ do_checkdisk() {
         error_msg "Unable to recognize the disk type of ${ROOT_PTNAME}!"
         ;;
     esac
+    echo -e "${INFO} OpenWrt running: [ ${LB_PRE:0:-1} - /dev/${DISK_NAME} ]."
+
+    # Check whether partition is required
+    [[ -n "$(lsblk -l -o NAME | grep -oE "^${PT_PRE}4")" ]] && {
+        # Delete auto-extending file
+        rm -f ${todo_rootfs_resize} 2>/dev/null
+        echo -e "${TIPS} Partitioned, no operation required."
+        exit 0
+    }
 }
 
-# Get the starting position of the p3 partition
+# Create the 3rd and 4th partition
 create_new_part() {
     # Generate New UUID
+    echo -e "${STEPS} Start generating new partition UUID..."
     ROOTFS_UUID="$(cat /proc/sys/kernel/random/uuid)"
     [[ -z "${ROOTFS_UUID}" ]] && ROOTFS_UUID="$(uuidgen)"
     SHARED_UUID="$(cat /proc/sys/kernel/random/uuid)"
     [[ -z "${SHARED_UUID}" ]] && SHARED_UUID="$(uuidgen)"
     [[ -z "${ROOTFS_UUID}" || -z "${SHARED_UUID}" ]] && error_msg "The new UUID is invalid, cannot continue."
 
-    ROOTFS_MB="960"
-    START_P3="$(fdisk -l | grep "${ROOT_PTNAME}" | sed -n '$p' | awk '{print $3}' | echo $(($(xargs) + 1)))"
-    [[ -z "${START_P3}" || -z "$(echo ${START_P3} | sed -n "/^[0-9]\+$/p")" ]] && error_msg "Unable to get starting position!"
+    # Repair disk size
+    echo -e "${STEPS} Start repairing hard disk size..."
+    printf 'f\n' | parted ---pretend-input-tty /dev/${DISK_NAME} print || repair_status="no"
+    [[ "${repair_status}" == "no" ]] && error_msg "Disk size repair failed, stop partitioning."
 
-    END_P3="$((ROOTFS_MB * 2048 + START_P3 - 1))"
+    # Calculate partition positions
+    echo -e "${STEPS} Start calculating partition location..."
+    END_P2="$(fdisk -l | grep "${ROOT_PTNAME}" | sed -n '$p' | awk '{print $3}' | xargs)"
+    [[ -z "${END_P2}" || -z "$(echo ${END_P2} | sed -n "/^[0-9]\+$/p")" ]] && error_msg "Unable to get starting position!"
+    START_P3="$(((END_P2 + 1) / 2048 + 1))"
 
-    TOTAL_SIZE="$(lsblk -l -b -o NAME,SIZE | awk "\$1 ~ /^${DISK_NAME}\$/ {print \$2}")"
-    START_P4="$((END_P3 + 1))"
-    END_P4="$((TOTAL_SIZE / 512 - 1))"
+    # Create the partition
+    echo -e "${STEPS} Start creating new partitions..."
+    ROOTFS_MB="1024"
+    parted /dev/${DISK_NAME} mkpart primary btrfs $((START_P3))MiB $((START_P3 + ROOTFS_MB - 1))MiB 2>/dev/null
+    parted /dev/${DISK_NAME} mkpart primary btrfs $((START_P3 + ROOTFS_MB))MiB 100% 2>/dev/null
+    # Show partition results
+    parted /dev/${DISK_NAME} unit MiB print
 
-    cat >/tmp/fdisk.script <<EOF
-n
-p
-3
-${START_P3}
-${END_P3}
-Y
-n
-p
-${START_P4}
-${END_P4}
-t
-3
-83
-t
-4
-83
-w
-EOF
-    sync
-
-    echo -e "${STEPS} Fdisk starting ..."
-    fdisk /dev/${DISK_NAME} </tmp/fdisk.script 2>/dev/null
-    [[ "${?}" -ne "0" ]] && error_msg "Fdisk failed!"
-
-    echo -e "${STEPS} Create extended partition ..."
-    # Create the third partition
+    echo -e "${STEPS} Start formatting new partition..."
+    # Format the third partition
     mkdir -p /mnt/${PT_PRE}3
-    mkfs.btrfs -f -U ${ROOTFS_UUID} -L "${LB_PRE}ROOTFS2" -m single "/dev/${PT_PRE}3" >/dev/null 2>&1
+    umount -f /dev/${PT_PRE}3 2>/dev/null
+    mkfs.btrfs -f -U ${ROOTFS_UUID} -L "${LB_PRE}ROOTFS2" -m single "/dev/${PT_PRE}3"
+    [[ "${?}" -eq "0" ]] || error_msg "The [ /dev/${PT_PRE}3 ] partition format failed!"
     mount -t btrfs -o compress=zstd:6 "/dev/${PT_PRE}3" "/mnt/${PT_PRE}3"
-    # Create the fourth partition
-    mkdir -p /mnt/${PT_PRE}4
-    mkfs.btrfs -f -U ${SHARED_UUID} -L "${LB_PRE}SHARED" -m single "/dev/${PT_PRE}4" >/dev/null 2>&1
-    mount -t btrfs -o compress=zstd:6 "/dev/${PT_PRE}4" "/mnt/${PT_PRE}4"
+    [[ "${?}" -eq "0" ]] || error_msg "Mount [ /mnt/${PT_PRE}3 ] failed!"
 
-    echo -e "${STEPS} Init the docker config ..."
+    # Format the fourth partition
+    mkdir -p /mnt/${PT_PRE}4
+    umount -f /dev/${PT_PRE}4 2>/dev/null
+    mkfs.btrfs -f -U ${SHARED_UUID} -L "${LB_PRE}SHARED" -m single "/dev/${PT_PRE}4"
+    [[ "${?}" -eq "0" ]] || error_msg "The [ /dev/${PT_PRE}4 ] partition format failed!"
+    mount -t btrfs -o compress=zstd:6 "/dev/${PT_PRE}4" "/mnt/${PT_PRE}4"
+    [[ "${?}" -eq "0" ]] || error_msg "Mount [ /mnt/${PT_PRE}4 ] failed!"
+
+    # Adjust docker data storage location
+    echo -e "${STEPS} Start adjusting docker settings..."
     /etc/init.d/dockerd stop 2>/dev/null
     /etc/init.d/dockerd disable 2>/dev/null
     rm -rf "/opt/docker" 2>/dev/null
@@ -143,22 +150,21 @@ EOF
     /etc/init.d/dockerd start 2>/dev/null
     /etc/init.d/dockerd enable 2>/dev/null
 
-    echo -e "${SUCCESS} Create partition successfully"
+    # Delete auto-extending file
+    rm -f ${todo_rootfs_resize} 2>/dev/null
+
+    echo -e "${INFO} Current partition status: \n$(lsblk)"
+    echo -e "${SUCCESS} Create partition successfully."
     sync
     exit 0
 }
 
+# Show welcome message
 echo -e "${STEPS} Welcome to use TF/SD/USB partition management tool."
 # Check script permission
 [[ -x "/usr/sbin/openwrt-tf" ]] || error_msg "Please grant execution permission: [ chmod +x /usr/sbin/openwrt-tf ]"
 #
-echo -ne "${STEPS} This operation will clear the data in the remaining space, are you sure to continue? y/n [y]\b\b"
-read yn
-case "${yn}" in
-    n* | N*) error_msg " You aborted the operation!" ;;
-esac
-#
 # Check disk
 do_checkdisk
-# Get the starting position of the p3 partition
+# Create the 3rd and 4th partition
 create_new_part
