Adjust github process variables

diff --git a/.github/workflows/packaging-openwrt-for-qemu-etc.yml b/.github/workflows/packaging-openwrt-for-qemu-etc.yml
--- a/.github/workflows/packaging-openwrt-for-qemu-etc.yml
+++ b/.github/workflows/packaging-openwrt-for-qemu-etc.yml
@@ -10,7 +10,7 @@ on:
   workflow_dispatch:
     inputs:
       branch:
-        description: "Select the source branch"
+        description: "Select Source Branch"
         required: false
         default: "lasthinker"
         type: choice
@@ -18,7 +18,7 @@ on:
           - lasthinker
           - official
       openwrt_soc:
-        description: "Select device SoC"
+        description: "Select Device SoC"
         required: false
         default: "s905x"
         type: choice
@@ -26,7 +26,7 @@ on:
           - all
           - s905x
       openwrt_kernel:
-        description: "Select kernel version"
+        description: "Select Kernel version"
         required: false
         default: "5.4.195"
         type: choice
@@ -36,7 +36,7 @@ on:
           - 5.4.199_5.15.50
           - 5.4.199
       auto_kernel:
-        description: "Auto use the latest kernel"
+        description: "Auto Use Latest Kernel"
         required: false
         default: true
         type: boolean
@@ -47,7 +47,7 @@ env:
 jobs:
   build:
     runs-on: ubuntu-22.04
-    if: github.event.repository.owner.id == github.event.sender.id
+    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
 
     steps:
       - name: Checkout
@@ -64,24 +64,25 @@ jobs:
           sudo -E apt-get -qq autoremove --purge
           sudo -E apt-get -qq clean
           sudo timedatectl set-timezone "${TZ}"
-          echo "::set-output name=status::success"
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Download Armvirt File
-        id: download
+        id: down
+        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
         run: |
-          openwrt_url="$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_.*${{ github.event.inputs.branch }}.*/.*rootfs.tar.gz" | head -n 1)"
+          openwrt_url="$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "OpenWrt_.*${{ github.event.inputs.branch }}.*/.*rootfs.tar.gz" | head -n 1)"
           [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
           #
           armvirt_tarfile_path="openwrt/bin/targets/armvirt/64"
           [[ -d "${armvirt_tarfile_path}" ]] || mkdir -p ${armvirt_tarfile_path}
           #
           wget -q -P "${armvirt_tarfile_path}" "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}"
-          [[ "${?}" -ne "0" ]] && echo "The armvirt file download failed!" && exit 1
-          echo "::set-output name=status::success"
+          [[ "${?}" -ne "0" ]] && echo -e "The armvirt file download failed!" && exit 1
+          echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Packaging OpenWrt
         uses: lasthinker/amlogic-s9xxx-openwrt@main
-        if: steps.download.outputs.status == 'success' && !cancelled()
+        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
         env:
           OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*rootfs.tar.gz
           KERNEL_REPO_URL: https://github.com/lasthinker/kernel/tree/main/pub/stable
@@ -91,17 +92,15 @@ jobs:
 
       - name: Upload OpenWrt Firmware to Release
         uses: ncipollo/release-action@main
-        if: env.PACKAGED_STATUS == 'success' && !cancelled()
+        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
         with:
-          tag: openwrt_aarch64_${{ env.PACKAGED_OUTPUTDATE }}
+          tag: OpenWrt_aarch64_${{ env.PACKAGED_OUTPUTDATE }}
           artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
           token: ${{ secrets.GH_TOKEN }}
           body: |
-            This is OpenWrt firmware for Armvirt 64
+            This is OpenWrt Firmware for Armvirt 64
             * Firmware Information
-            Default IP: 192.168.2.1
+            Default IP: 192.168.1.1
             Default Username: root
             Default Password: password
-            Default WIFI SSID: OpenWrt
-            Default WIFI Password: none
