Optimize Actions code

diff --git a/.github/workflows/push-openwrt-to-docker-hub.yml b/.github/workflows/push-openwrt-to-docker-hub.yml
--- a/.github/workflows/push-openwrt-to-docker-hub.yml
+++ b/.github/workflows/push-openwrt-to-docker-hub.yml
@@ -11,31 +11,21 @@ on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
-      openwrt_file:
-        description: "Select the OpenWrt rootfs file"
+      branch:
+        description: "Select the source branch"
         required: false
         default: "lasthinker"
         type: choice
         options:
           - lasthinker
           - official
-      docker_user:
-        description: "Set the docker username"
+      docker_img:
+        description: "Set the docker image"
         required: false
-        default: "lasthinker"
-      docker_app:
-        description: "Set the docker app name"
-        required: false
-        default: "openwrt-aarch64"
-      docker_tag:
-        description: "Select the docker image tag"
-        required: false
-        default: "latest"
-        type: choice
-        options:
-          - latest
-          - linux-arm64
-          - arm64v8-latest
+        default: "lasthinker/openwrt-aarch64:latest"
+
+env:
+  DOCKER_OUTPATH: out
 
 jobs:
   build:
@@ -50,28 +40,20 @@ jobs:
         id: down
         if: (!cancelled())
         run: |
-          # Get input parameters
-          openwrt_file="${{ github.event.inputs.openwrt_file }}"
-          docker_user="${{ github.event.inputs.docker_user }}"
-          docker_app="${{ github.event.inputs.docker_app }}"
-          docker_tag="${{ github.event.inputs.docker_tag }}"
-          docker_out="${docker_user}/${docker_app}:${docker_tag}"
-          echo "DOCKER_OUT=${docker_out}" >> $GITHUB_ENV
-
           # Get OpenWrt file
-          openwrt_url="$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_s9xxx_${openwrt_file}.*/.*rootfs.tar.gz" | head -n 1)"
-          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found." && exit 1
-          rm -rf docker_image && mkdir -p docker_image
-          wget -q "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}" -O docker_image/openwrt-armvirt-64-default-rootfs.tar.gz
-
+          openwrt_url="$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "openwrt_.*${{ github.event.inputs.branch }}.*/.*rootfs.tar.gz" | head -n 1)"
+          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
+          rm -rf ${{ env.DOCKER_OUTPATH }} 2>/dev/null && mkdir -p ${{ env.DOCKER_OUTPATH }}
+          wget -q "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}" -O "${{ env.DOCKER_OUTPATH }}/openwrt-armvirt-64-default-rootfs.tar.gz"
+          #
           # Generate Dockerfile
-          echo 'FROM scratch' >docker_image/Dockerfile
-          echo 'ADD openwrt-armvirt-64-default-rootfs.tar.gz /' >>docker_image/Dockerfile
-          echo 'EXPOSE 22 53 80 443 7681' >>docker_image/Dockerfile
-          echo 'ENTRYPOINT ["/sbin/init"]' >>docker_image/Dockerfile
-          sync
-
-          echo -e "Current docker_image directory status: \n$(ls docker_image -l)"
+          docker_envfile="${{ env.DOCKER_OUTPATH }}/Dockerfile"
+          echo 'FROM scratch' >${docker_envfile}
+          echo 'ADD openwrt-armvirt-64-default-rootfs.tar.gz /' >>${docker_envfile}
+          echo 'EXPOSE 22 53 80 443 7681' >>${docker_envfile}
+          echo 'ENTRYPOINT ["/sbin/init"]' >>${docker_envfile}
+          #
+          sync && echo -e "Current ${{ env.DOCKER_OUTPATH }} directory status: \n$(ls ${{ env.DOCKER_OUTPATH }} -l)"
           echo "::set-output name=status::success"
 
       - name: Set up QEMU
@@ -97,7 +79,7 @@ jobs:
         if: (!cancelled())
         uses: docker/build-push-action@v3
         with:
-          context: docker_image/
           push: true
-          tags: ${{ env.DOCKER_OUT }}
           platforms: linux/arm64
+          context: ${{ env.DOCKER_OUTPATH }}
+          tags: "${{ github.event.inputs.docker_img }}"
